---
# Excluding scheme will default to https
pidfile: /tmp/memcache-hazelcast.pid

logging:
  level: INFO

memcache:
  port: 54914
  secret_key: 

hazelcast:
  port: 5701
  local_member_safe_timeout: 120
  minimum_cluster_members: 1
  executor_pool_size: 0
  max_cache_size: 536870912
  percent_to_trim: 20
  trim_delay: 10
  partition_count: 271
  io_thread_count: 3
  operation_thread_count: -1
  operation_generic_thread_count: -1
  event_thread_count: 5
  client_event_thread_count: 5
  max_no_heartbeat_seconds: 300
  machines:
    rz1:
    - 127.0.0.1

host:
  local: 10.255.196.31
  public: memcache.cf-dev.lds.org
  port: 20081
  username: basic
  password: password

nats:
  machines:
  - nats://nats:password@10.118.216.220:4222

plans:
  small:
    backup: 0
    async_backup: 0
    eviction_policy: LRU
    max_idle_seconds: 86400
    max_size_used_heap: 1000
  medium:
    backup: 0
    async_backup: 1
    eviction_policy: LRU
    max_idle_seconds: 86400
    max_size_used_heap: 100
  large:
    backup: 0
    async_backup: 1
    eviction_policy: LRU
    max_idle_seconds: 86400
    max_size_used_heap: 1000
  darren:
    backup: 0
    async_backup: 1
    eviction_policy: LRU
    time_to_live: 86400
    max_size_used_heap: 1000
